name: build-docker-images

on:
  push:
    branches:
      - master
  pull_request:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [opened, edited]
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published, created, edited]
  watch:
    types: [started]

# TODO: create generic job for build jobs
jobs:
  build_proxy:
    name: Build proxy image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get change count for proxy
        id: filesChanged
        run: |
          echo "::set-output name=proxy::$( git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -c proxy)"

      - name: Build and push proxy
        if: steps.filesChanged.outputs.proxy > 0 || github.actor == 'shotor'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.docker_hub_user }}
          password: ${{ secrets.docker_hub_key }}
          repository: tihunlp/tihu-proxy
          tag_with_ref: true
          dockerfile: proxy/Dockerfile

  build_mock_api:
    name: Build mock api image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get change count for mock
        id: filesChanged
        run: |
          echo "::set-output name=grpc::$( git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -c grpc)"

      - name: Build and push proxy
        if: steps.filesChanged.outputs.grpc > 0 || github.actor == 'shotor'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.docker_hub_user }}
          password: ${{ secrets.docker_hub_key }}
          repository: tihunlp/tihu-mock-api
          tag_with_ref: true
          dockerfile: proxy/Dockerfile
